spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mariadb://74.208.33.72:63306/xpress_dinero
    username: xpress_dinero_noco
    password: x&p20q6H2
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    mongodb:
      uri: mongodb+srv://reports_xpress_user_rw:ULh0VykDvetWM3JM@cluster0.zoa5e.gcp.mongodb.net/ReportsXpress