name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Jar
        run: mvn clean package
  run:
    needs: [ build ]
    runs-on: self-hosted
    steps:
      - name: Run
        run: nohup java -jar target/SFast-Xpress-0.0.1-SNAPSHOT.jar &
