name: Mover JAR a servidor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    runs-on: self-hosted
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Compilar y empaquetar
        run: mvn clean package
  CD:
    needs: [CI]
    runs-on: self-hosted
    steps:
      - name: Levantar servicio
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            kill -9 $(lsof -t -i:8080)
            cd ~/actions-runner/_work/SFast-Xpress/SFast-Xpress/
            chmod +x ./mvnw
            ./mvnw spring-boot:run > /dev/null 2>&1 &
            echo "El script se ha lanzado correctamente."
